---

default:
  image: docker:23
  tags:
    - docker-socket

  before_script:
    - apk add git
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

stages:
  - build

build:
  stage: build
  script:
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        tag="$CI_COMMIT_TAG"
      else
        tag="$CI_COMMIT_REF_SLUG-$(date -u +"%Y%m%d-%H%M%S")-$CI_COMMIT_SHORT_SHA"
      fi
      echo "$tag"
      docker build -t "${CI_REGISTRY_IMAGE}:$tag" .
      docker push "${CI_REGISTRY_IMAGE}:$tag"
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
